name: CI


on: [push, pull_request]


jobs:
  ##############################################################################
  # macos with gcc and blas
  ##############################################################################
  macos-gcc:
    name: macOS GCC with BLAS (x3)

    runs-on: macos-latest

    env:
      MAKE: "gmake -j -l 10 --output-sync=target"
      CFLAGS: "-Wall"
      EXTRA_OPTIONS: "--disable-static --enable-shared"
      CC: "gcc"

    steps:
      - uses: actions/checkout@v3

      - name: "Setup"
        run: |
          brew install gcc
          brew install make
          brew install gmp
          brew install mpfr
          brew install autoconf
          brew install libtool
          brew install automake
          brew install openblas
          gcc --version
          gmake --version
          autoconf --version

      - name: "Configure"
        run: |
          ./bootstrap.sh
          ./configure CC=${CC} CFLAGS="${CFLAGS}" \
              --with-gmp=$(brew --prefix) \
              --with-mpfr=$(brew --prefix) \
              --with-blas=$(brew --prefix)/opt/openblas \
              ${EXTRA_OPTIONS}

      - name: "Compile library"
        run: |
          $MAKE

      - name: "Compile tests"
        run: |
          export FLINT_TEST_MULTIPLIER=3
          $MAKE tests

      - name: "Check"
        run: |
          export FLINT_TEST_MULTIPLIER=3
          $MAKE check

      - if: failure()
        name: "If failure, stop all other jobs"
        uses: andymckay/cancel-action@0.3
