name: flint-tests
on: [push, pull_request]
jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "LOCAL=${GITHUB_WORKSPACE}/local" >> $GITHUB_ENV
          echo "LDFLAGS=-Wl,-rpath,$LOCAL/lib" >> $GITHUB_ENV
          echo "MAKE=make-j" >> $GITHUB_ENV
          sudo apt-get install texinfo
          ./.build_dependencies
          ./configure CFLAGS="-Wredundant-decls" --with-mpir=${LOCAL} --with-mpfr=${LOCAL} --prefix=${LOCAL}
          $MAKE
          ldd libflint.so
          $MAKE check
       env:
          LOCAL: ${{ github.workspace }}/local
          LDFLAGS: "-Wl,-rpath,$LOCAL/lib"
          MAKE: "make -j"
  ubuntu-cmake-gcc:
    runs-on: ubuntu-latest
    env:
      LOCAL: ${GITHUB_WORKSPACE}/local
      LDFLAGS: "-Wl,-rpath,$LOCAL/lib"
      MAKE: "make -j"
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install texinfo
      - run: sudo apt-get install cmake
      - run: ./.build_dependencies
      - run: mkdir build
      - run: cd build
      - run: cmake -G"Unix Makefiles" -DWITH_NTL=yes -DBUILD_TESTING=yes -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$LOCAL ..
      - run: $MAKE
      - run: ldd lib/libflint.so
      - run: cd ..
    
